# This file was generated by GoReleaser. DO NOT EDIT.
cask "bouncerfox" do
  name "bouncerfox"
  desc "Scan AI agent config files for security and quality issues"
  homepage "https://github.com/bouncerfox/cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bouncerfox"

  on_macos do
    on_intel do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_darwin_amd64.tar.gz"
      sha256 "c92b75625bd747eaa1eed016571c83ba9ffe595a5e28223c9b9b88ad77697de1"
    end
    on_arm do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_darwin_arm64.tar.gz"
      sha256 "e88a5c1c8bbf76c0219520da8b3f254fce9ffd77a527836574974c964e63c927"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_linux_amd64.tar.gz"
      sha256 "eb295a2205389b6453937438d179a389bb2454242af155fc53c5f3927109bab5"
    end
    on_arm do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_linux_arm64.tar.gz"
      sha256 "5279b7de196a077d80c932212e58ed87e421393a1a769c8dbd4b1fcd9b74ff74"
    end
  end

  # No zap stanza required
end
