# This file was generated by GoReleaser. DO NOT EDIT.
cask "bouncerfox" do
  version "0.6.1"

  on_macos do
    on_intel do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_darwin_amd64.tar.gz"
      sha256 "94ecc44f82ac3d029c6a1a4ed01a00efc84b4d41ec895537400c43ac47dfae14"
    end
    on_arm do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_darwin_arm64.tar.gz"
      sha256 "99df7b8160ac6994152728bffb196f12db8713022091f6ef9d57f15db09cac2b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_linux_amd64.tar.gz"
      sha256 "f2d7c12321156a7384cca097b33cfc240d54ae7bc319568bb0b344ec556c4afc"
    end
    on_arm do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_linux_arm64.tar.gz"
      sha256 "85adfeb1a609629e1a3a17cb1a628389f363d386ffa105a50aa0018f74d51873"
    end
  end

  name "bouncerfox"
  desc "Scan AI agent config files for security and quality issues"
  homepage "https://github.com/bouncerfox/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bouncerfox"

  # No zap stanza required

end
