# This file was generated by GoReleaser. DO NOT EDIT.
cask "bouncerfox" do
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_darwin_amd64.tar.gz"
      sha256 "45f2a8abc27cc1d91d60329e191e6f07e28e214747e92f252261c44da574427b"
    end
    on_arm do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_darwin_arm64.tar.gz"
      sha256 "16ff04b46245886e018266b24f6eb493e1d78877257ccede172ef081b764a0c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_linux_amd64.tar.gz"
      sha256 "5fdb001b8a8fee8219f2e3ba4d6d84e214b83f3d1376b2c4800233291c69cf5c"
    end
    on_arm do
      url "https://github.com/BouncerFox/cli/releases/download/v#{version}/bouncerfox_#{version}_linux_arm64.tar.gz"
      sha256 "00489c4d6b928861108d2de617b067aef210e28f3caec0be21240a6e1ac085b7"
    end
  end

  name "bouncerfox"
  desc "Scan AI agent config files for security and quality issues"
  homepage "https://github.com/bouncerfox/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bouncerfox"

  # No zap stanza required

end
